sites:
  - title: "Blinko Demo"
    url: "https://blinko.up.railway.app"
    description: "Official Blinko demo site"
    tags: 
      - demo
      - official
    created_at: "2024-01-14"
    category: "Official"
    
  - title: "Blinko Community"
    url: "https://community.blinko.space"
    description: "Blinko community instance"
    tags:
      - community
    created_at: "2024-01-14"
    category: "Community" 